### ISSUE TITLE
Connection has no method 'listen'

### ISSUE THREAD

**Issue by yuniers** [node-xmpp/node-xmpp-client#105]
I want send jabber messages and when I execute the server, an error say to me that something is wrong.

My code is:
```javascript
var Client = require('node-xmpp-client')
 , ltx  = Client.ltx
 
var client = new Client({
   host: 'jabber.uci.cu',
	//port: 5222,
	//legacySSL: true,
	//reconnect: false,
	//preferred: 'PLAIN',
	jid: 'yjsosa@jabber.uci.cu',
	password: 'password'
})
 
client.on('online', function() {
    console.log('online')
})
 
client.on('stanza', function(stanza) {
    console.log('Incoming stanza: ', stanza.toString())
})
```
Error:

pikete@Pikete-PC:~/prueba-agenda$ nodejs server
/home/pikete/prueba-agenda/node_modules/node-xmpp-client/lib/session.js:81
        this.connection.listen({
                        ^
TypeError: Object #<Connection> has no method 'listen'
    at Client.Session._socketConnectionToHost (/home/pikete/prueba-agenda/node_modules/node-xmpp-client/lib/session.js:81:25)
    at Client.Session._setupSocketConnection (/home/pikete/prueba-agenda/node_modules/node-xmpp-client/lib/session.js:49:14)
    at Client.Session (/home/pikete/prueba-agenda/node_modules/node-xmpp-client/lib/session.js:26:14)
    at Client.connect (/home/pikete/prueba-agenda/node_modules/node-xmpp-client/index.js:185:17)
    at new Client (/home/pikete/prueba-agenda/node_modules/node-xmpp-client/index.js:136:14)
    at Object.<anonymous> (/home/pikete/prueba-agenda/server.js:4:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

**Comment by lloydwatkin** [comment]
@sonnyp I think one of the latest commits to `node-xmpp-core` has broken things for users. Could you take a look please?

See also #104

**Comment by yuniers** [comment]
@lloydwatkin I try installing `node-xmpp-core 1.0.0-alpha10` and work nice, the problem is `node-xmpp-core 1.0.0-alpha14`

**Comment by lloydwatkin** [comment]
Reopening as there is clearly an issue somewhere between node-xmpp-core alphas 10 and 14

cc @chris-rock @sonnyp

**Comment by lloydwatkin** [comment]
Closing again as @sonnyp has been hard at work
