### ISSUE TITLE
The latest supported node?

### ISSUE THREAD

**Issue by iliakan** [node-xmpp/node-xmpp-client#124]
Is iojs 2.5.0 the latest supported version?

**Comment by sonnyp** [comment]
4 should work fine, any issues?

**Comment by iliakan** [comment]
It fails to install on versions greater than 2.5.0

That's the log for 4.1.0:
```
~
iliakan> mkdir tmp

~
iliakan> cd tmp

~/tmp
iliakan> mkdir node_modules

~/tmp
iliakan> npm i node-xmpp-client
npm http request GET https://registry.npmjs.org/node-xmpp-client
npm http 304 https://registry.npmjs.org/node-xmpp-client
npm http request GET https://registry.npmjs.org/faye-websocket
npm http request GET https://registry.npmjs.org/node-xmpp-core
npm http request GET https://registry.npmjs.org/browser-request
npm http request GET https://registry.npmjs.org/request
npm http request GET https://registry.npmjs.org/minimist
npm http request GET https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/faye-websocket
npm http 304 https://registry.npmjs.org/minimist
npm http 304 https://registry.npmjs.org/request
npm http 304 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/node-xmpp-core
npm http 304 https://registry.npmjs.org/browser-request
npm http request GET https://registry.npmjs.org/ms
npm http request GET https://registry.npmjs.org/lodash.assign
npm http request GET https://registry.npmjs.org/ltx
npm http request GET https://registry.npmjs.org/node-stringprep
npm http request GET https://registry.npmjs.org/tls-connect
npm http request GET https://registry.npmjs.org/inherits
npm http fetch GET https://github.com/dodo/reconnect-core/tarball/merged
npm http request GET https://registry.npmjs.org/websocket-driver
npm http request GET https://registry.npmjs.org/forever-agent
npm http request GET https://registry.npmjs.org/caseless
npm http request GET https://registry.npmjs.org/form-data
npm http request GET https://registry.npmjs.org/json-stringify-safe
npm http request GET https://registry.npmjs.org/mime-types
npm http request GET https://registry.npmjs.org/node-uuid
npm http request GET https://registry.npmjs.org/qs
npm http request GET https://registry.npmjs.org/tunnel-agent
npm http request GET https://registry.npmjs.org/tough-cookie
npm http request GET https://registry.npmjs.org/http-signature
npm http request GET https://registry.npmjs.org/oauth-sign
npm http request GET https://registry.npmjs.org/hawk
npm http request GET https://registry.npmjs.org/aws-sign2
npm http request GET https://registry.npmjs.org/stringstream
npm http request GET https://registry.npmjs.org/combined-stream
npm http request GET https://registry.npmjs.org/isstream
npm http request GET https://registry.npmjs.org/har-validator
npm http request GET https://registry.npmjs.org/bl
npm http 304 https://registry.npmjs.org/ms
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/lodash.assign
npm http 304 https://registry.npmjs.org/tls-connect
npm http 304 https://registry.npmjs.org/forever-agent
npm http 304 https://registry.npmjs.org/caseless
npm http 304 https://registry.npmjs.org/form-data
npm http 304 https://registry.npmjs.org/json-stringify-safe
npm http 304 https://registry.npmjs.org/mime-types
npm http 304 https://registry.npmjs.org/qs
npm http 304 https://registry.npmjs.org/node-uuid
npm http 304 https://registry.npmjs.org/http-signature
npm http 304 https://registry.npmjs.org/tunnel-agent
npm http 304 https://registry.npmjs.org/tough-cookie
npm http 304 https://registry.npmjs.org/stringstream
npm http 304 https://registry.npmjs.org/oauth-sign
npm http 304 https://registry.npmjs.org/hawk
npm http 304 https://registry.npmjs.org/aws-sign2
npm http 304 https://registry.npmjs.org/combined-stream
npm http 304 https://registry.npmjs.org/har-validator
npm http 304 https://registry.npmjs.org/websocket-driver
npm http 304 https://registry.npmjs.org/bl
npm http 304 https://registry.npmjs.org/isstream
npm http request GET https://registry.npmjs.org/delayed-stream
npm http request GET https://registry.npmjs.org/async
npm http request GET https://registry.npmjs.org/mime-db
npm http 304 https://registry.npmjs.org/node-stringprep
npm http 304 https://registry.npmjs.org/ltx
npm http request GET https://registry.npmjs.org/readable-stream
npm http request GET https://registry.npmjs.org/assert-plus
npm http request GET https://registry.npmjs.org/asn1
npm http request GET https://registry.npmjs.org/ctype
npm http request GET https://registry.npmjs.org/websocket-extensions
npm http request GET https://registry.npmjs.org/commander
npm http request GET https://registry.npmjs.org/is-my-json-valid
npm http request GET https://registry.npmjs.org/chalk
npm http request GET https://registry.npmjs.org/bluebird
npm http request GET https://registry.npmjs.org/hoek
npm http request GET https://registry.npmjs.org/boom
npm http request GET https://registry.npmjs.org/cryptiles
npm http request GET https://registry.npmjs.org/sntp
npm http 304 https://registry.npmjs.org/delayed-stream
npm http 304 https://registry.npmjs.org/mime-db
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/readable-stream
npm http request GET https://registry.npmjs.org/isarray
npm http request GET https://registry.npmjs.org/string_decoder
npm http request GET https://registry.npmjs.org/core-util-is
npm http 304 https://registry.npmjs.org/ctype
npm http 304 https://registry.npmjs.org/assert-plus
npm http 304 https://registry.npmjs.org/is-my-json-valid
npm http 304 https://registry.npmjs.org/commander
npm http 304 https://registry.npmjs.org/chalk
npm http 304 https://registry.npmjs.org/cryptiles
npm http 304 https://registry.npmjs.org/sntp
npm http 304 https://registry.npmjs.org/bluebird
npm http 304 https://registry.npmjs.org/boom
npm http 304 https://registry.npmjs.org/hoek
npm http 304 https://registry.npmjs.org/websocket-extensions
npm http 304 https://registry.npmjs.org/isarray
npm http request GET https://registry.npmjs.org/escape-string-regexp
npm http request GET https://registry.npmjs.org/has-ansi
npm http request GET https://registry.npmjs.org/strip-ansi
npm http request GET https://registry.npmjs.org/supports-color
npm http 304 https://registry.npmjs.org/string_decoder
npm http request GET https://registry.npmjs.org/ansi-styles
npm http request GET https://registry.npmjs.org/graceful-readlink
npm http 304 https://registry.npmjs.org/core-util-is
npm http 304 https://registry.npmjs.org/asn1
npm http 304 https://registry.npmjs.org/supports-color
npm http 304 https://registry.npmjs.org/strip-ansi
npm http 304 https://registry.npmjs.org/ansi-styles
npm http 304 https://registry.npmjs.org/graceful-readlink
npm http request GET https://registry.npmjs.org/generate-object-property
npm http request GET https://registry.npmjs.org/generate-function
npm http request GET https://registry.npmjs.org/jsonpointer
npm http request GET https://registry.npmjs.org/xtend
npm http 304 https://registry.npmjs.org/has-ansi
npm http 304 https://registry.npmjs.org/jsonpointer
npm http 304 https://registry.npmjs.org/generate-function
npm http 304 https://registry.npmjs.org/generate-object-property
npm http 304 https://registry.npmjs.org/xtend
npm http request GET https://registry.npmjs.org/is-property
npm http 304 https://registry.npmjs.org/is-property
npm http 304 https://registry.npmjs.org/escape-string-regexp
npm http request GET https://registry.npmjs.org/ansi-regex
npm http 304 https://registry.npmjs.org/ansi-regex
npm http fetch 200 https://github.com/dodo/reconnect-core/tarball/merged
npm http request GET https://registry.npmjs.org/lodash._baseassign
npm http request GET https://registry.npmjs.org/lodash._createassigner
npm http request GET https://registry.npmjs.org/lodash.keys
npm http request GET https://registry.npmjs.org/backoff
npm http request GET https://registry.npmjs.org/bindings
npm http request GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/lodash._baseassign
npm http 304 https://registry.npmjs.org/lodash.keys
npm http 304 https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/lodash._createassigner
npm http request GET https://registry.npmjs.org/lodash._basecopy
npm http request GET https://registry.npmjs.org/lodash.isarguments
npm http request GET https://registry.npmjs.org/lodash._getnative
npm http request GET https://registry.npmjs.org/lodash.isarray
npm http request GET https://registry.npmjs.org/lodash._isiterateecall
npm http request GET https://registry.npmjs.org/lodash._bindcallback
npm http request GET https://registry.npmjs.org/lodash.restparam
npm http 304 https://registry.npmjs.org/lodash.isarguments
npm http 304 https://registry.npmjs.org/lodash.isarray
npm http 304 https://registry.npmjs.org/lodash._getnative
npm http 304 https://registry.npmjs.org/lodash._isiterateecall
npm http 304 https://registry.npmjs.org/lodash._bindcallback
npm http 304 https://registry.npmjs.org/lodash.restparam
npm http 304 https://registry.npmjs.org/lodash._basecopy
npm http 304 https://registry.npmjs.org/bindings
npm http 304 https://registry.npmjs.org/backoff

> node-stringprep@0.7.2 install /Users/iliakan/tmp/node_modules/node-xmpp-client/node_modules/node-xmpp-core/node_modules/node-stringprep
> node-gyp rebuild

  CXX(target) Release/obj.target/node_stringprep/node-stringprep.o
In file included from ../node-stringprep.cc:1:
../node_modules/nan/nan.h:261:25: error: redefinition of '_NanEnsureLocal'
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../node_modules/nan/nan.h:256:25: note: previous definition is here
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                        ^
../node_modules/nan/nan.h:661:13: error: no member named 'smalloc' in namespace 'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^
../node_modules/nan/nan.h:672:12: error: no matching function for call to 'New'
    return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
           ^~~~~~~~~~~~~~~~~
/Users/iliakan/.node-gyp/4.1.0/include/node/node_buffer.h:31:40: note: candidate function not viable: no known conversion from 'uint32_t' (aka 'unsigned int') to 'enum encoding'
      for 3rd argument
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/iliakan/.node-gyp/4.1.0/include/node/node_buffer.h:43:40: note: candidate function not viable: 2nd argument ('const char *') would lose const qualifier
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/iliakan/.node-gyp/4.1.0/include/node/node_buffer.h:28:40: note: candidate function not viable: requires 2 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                       ^
/Users/iliakan/.node-gyp/4.1.0/include/node/node_buffer.h:36:40: note: candidate function not viable: requires 5 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
In file included from ../node-stringprep.cc:1:
../node_modules/nan/nan.h:676:12: error: no viable conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object>'
    return node::Buffer::New(v8::Isolate::GetCurrent(), size);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/iliakan/.node-gyp/4.1.0/include/node/v8.h:210:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from
      'v8::MaybeLocal<v8::Object>' to 'const v8::Local<v8::Object> &' for 1st argument
class Local {
      ^
/Users/iliakan/.node-gyp/4.1.0/include/node/v8.h:210:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from
      'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object> &&' for 1st argument
class Local {
      ^
/Users/iliakan/.node-gyp/4.1.0/include/node/v8.h:214:13: note: candidate template ignored: could not match 'Local' against 'MaybeLocal'
  V8_INLINE Local(Local<S> that)
            ^
/Users/iliakan/.node-gyp/4.1.0/include/node/v8.h:326:13: note: candidate template ignored: could not match 'S *' against 'v8::MaybeLocal<v8::Object>'
  V8_INLINE Local(S* that)
            ^
In file included from ../node-stringprep.cc:1:
../node_modules/nan/nan.h:683:26: error: no member named 'Use' in namespace 'node::Buffer'
    return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
           ~~~~~~~~~~~~~~^
../node-stringprep.cc:209:20: warning: 'uidna_toUnicode_55' is deprecated [-Wdeprecated-declarations]
        size_t w = uidna_toUnicode(*str, str.length(),
                   ^
/opt/local/include/unicode/urename.h:980:25: note: expanded from macro 'uidna_toUnicode'
#define uidna_toUnicode U_ICU_ENTRY_POINT_RENAME(uidna_toUnicode)
                        ^
/opt/local/include/unicode/uvernum.h:112:40: note: expanded from macro 'U_ICU_ENTRY_POINT_RENAME'
#define U_ICU_ENTRY_POINT_RENAME(x)    U_DEF2_ICU_ENTRY_POINT_RENAME(x,U_ICU_VERSION_SUFFIX)
                                       ^
/opt/local/include/unicode/uvernum.h:111:44: note: expanded from macro 'U_DEF2_ICU_ENTRY_POINT_RENAME'
#define U_DEF2_ICU_ENTRY_POINT_RENAME(x,y) U_DEF_ICU_ENTRY_POINT_RENAME(x,y)
                                           ^
/opt/local/include/unicode/uvernum.h:110:43: note: expanded from macro 'U_DEF_ICU_ENTRY_POINT_RENAME'
#define U_DEF_ICU_ENTRY_POINT_RENAME(x,y) x ## y
                                          ^
<scratch space>:93:1: note: expanded from here
uidna_toUnicode_55
^
/opt/local/include/unicode/uidna.h:622:1: note: 'uidna_toUnicode_55' has been explicitly marked deprecated here
uidna_toUnicode(const UChar* src, int32_t srcLength,
^
/opt/local/include/unicode/urename.h:980:25: note: expanded from macro 'uidna_toUnicode'
#define uidna_toUnicode U_ICU_ENTRY_POINT_RENAME(uidna_toUnicode)
                        ^
/opt/local/include/unicode/uvernum.h:112:40: note: expanded from macro 'U_ICU_ENTRY_POINT_RENAME'
#define U_ICU_ENTRY_POINT_RENAME(x)    U_DEF2_ICU_ENTRY_POINT_RENAME(x,U_ICU_VERSION_SUFFIX)
                                       ^
/opt/local/include/unicode/uvernum.h:111:44: note: expanded from macro 'U_DEF2_ICU_ENTRY_POINT_RENAME'
#define U_DEF2_ICU_ENTRY_POINT_RENAME(x,y) U_DEF_ICU_ENTRY_POINT_RENAME(x,y)
                                           ^
/opt/local/include/unicode/uvernum.h:110:43: note: expanded from macro 'U_DEF_ICU_ENTRY_POINT_RENAME'
#define U_DEF_ICU_ENTRY_POINT_RENAME(x,y) x ## y
                                          ^
<scratch space>:85:1: note: expanded from here
uidna_toUnicode_55
^
../node-stringprep.cc:254:22: warning: 'uidna_toASCII_55' is deprecated [-Wdeprecated-declarations]
    size_t destLen = uidna_toASCII(*str, strLen,
                     ^
/opt/local/include/unicode/urename.h:979:23: note: expanded from macro 'uidna_toASCII'
#define uidna_toASCII U_ICU_ENTRY_POINT_RENAME(uidna_toASCII)
                      ^
/opt/local/include/unicode/uvernum.h:112:40: note: expanded from macro 'U_ICU_ENTRY_POINT_RENAME'
#define U_ICU_ENTRY_POINT_RENAME(x)    U_DEF2_ICU_ENTRY_POINT_RENAME(x,U_ICU_VERSION_SUFFIX)
                                       ^
/opt/local/include/unicode/uvernum.h:111:44: note: expanded from macro 'U_DEF2_ICU_ENTRY_POINT_RENAME'
#define U_DEF2_ICU_ENTRY_POINT_RENAME(x,y) U_DEF_ICU_ENTRY_POINT_RENAME(x,y)
                                           ^
/opt/local/include/unicode/uvernum.h:110:43: note: expanded from macro 'U_DEF_ICU_ENTRY_POINT_RENAME'
#define U_DEF_ICU_ENTRY_POINT_RENAME(x,y) x ## y
                                          ^
<scratch space>:93:1: note: expanded from here
uidna_toASCII_55
^
/opt/local/include/unicode/uidna.h:574:1: note: 'uidna_toASCII_55' has been explicitly marked deprecated here
uidna_toASCII(const UChar* src, int32_t srcLength,
^
/opt/local/include/unicode/urename.h:979:23: note: expanded from macro 'uidna_toASCII'
#define uidna_toASCII U_ICU_ENTRY_POINT_RENAME(uidna_toASCII)
                      ^
/opt/local/include/unicode/uvernum.h:112:40: note: expanded from macro 'U_ICU_ENTRY_POINT_RENAME'
#define U_ICU_ENTRY_POINT_RENAME(x)    U_DEF2_ICU_ENTRY_POINT_RENAME(x,U_ICU_VERSION_SUFFIX)
                                       ^
/opt/local/include/unicode/uvernum.h:111:44: note: expanded from macro 'U_DEF2_ICU_ENTRY_POINT_RENAME'
#define U_DEF2_ICU_ENTRY_POINT_RENAME(x,y) U_DEF_ICU_ENTRY_POINT_RENAME(x,y)
                                           ^
/opt/local/include/unicode/uvernum.h:110:43: note: expanded from macro 'U_DEF_ICU_ENTRY_POINT_RENAME'
#define U_DEF_ICU_ENTRY_POINT_RENAME(x,y) x ## y
                                          ^
<scratch space>:84:1: note: expanded from here
uidna_toASCII_55
^
../node-stringprep.cc:264:9: warning: 'uidna_toASCII_55' is deprecated [-Wdeprecated-declarations]
        uidna_toASCII(*str, strLen,
        ^
/opt/local/include/unicode/urename.h:979:23: note: expanded from macro 'uidna_toASCII'
#define uidna_toASCII U_ICU_ENTRY_POINT_RENAME(uidna_toASCII)
                      ^
/opt/local/include/unicode/uvernum.h:112:40: note: expanded from macro 'U_ICU_ENTRY_POINT_RENAME'
#define U_ICU_ENTRY_POINT_RENAME(x)    U_DEF2_ICU_ENTRY_POINT_RENAME(x,U_ICU_VERSION_SUFFIX)
                                       ^
/opt/local/include/unicode/uvernum.h:111:44: note: expanded from macro 'U_DEF2_ICU_ENTRY_POINT_RENAME'
#define U_DEF2_ICU_ENTRY_POINT_RENAME(x,y) U_DEF_ICU_ENTRY_POINT_RENAME(x,y)
                                           ^
/opt/local/include/unicode/uvernum.h:110:43: note: expanded from macro 'U_DEF_ICU_ENTRY_POINT_RENAME'
#define U_DEF_ICU_ENTRY_POINT_RENAME(x,y) x ## y
                                          ^
<scratch space>:93:1: note: expanded from here
uidna_toASCII_55
^
/opt/local/include/unicode/uidna.h:574:1: note: 'uidna_toASCII_55' has been explicitly marked deprecated here
uidna_toASCII(const UChar* src, int32_t srcLength,
^
/opt/local/include/unicode/urename.h:979:23: note: expanded from macro 'uidna_toASCII'
#define uidna_toASCII U_ICU_ENTRY_POINT_RENAME(uidna_toASCII)
                      ^
/opt/local/include/unicode/uvernum.h:112:40: note: expanded from macro 'U_ICU_ENTRY_POINT_RENAME'
#define U_ICU_ENTRY_POINT_RENAME(x)    U_DEF2_ICU_ENTRY_POINT_RENAME(x,U_ICU_VERSION_SUFFIX)
                                       ^
/opt/local/include/unicode/uvernum.h:111:44: note: expanded from macro 'U_DEF2_ICU_ENTRY_POINT_RENAME'
#define U_DEF2_ICU_ENTRY_POINT_RENAME(x,y) U_DEF_ICU_ENTRY_POINT_RENAME(x,y)
                                           ^
/opt/local/include/unicode/uvernum.h:110:43: note: expanded from macro 'U_DEF_ICU_ENTRY_POINT_RENAME'
#define U_DEF_ICU_ENTRY_POINT_RENAME(x,y) x ## y
                                          ^
<scratch space>:84:1: note: expanded from here
uidna_toASCII_55
^
In file included from ../node-stringprep.cc:1:
In file included from ../node_modules/nan/nan.h:24:
In file included from /Users/iliakan/.node-gyp/4.1.0/include/node/node.h:42:
/Users/iliakan/.node-gyp/4.1.0/include/node/v8.h:221:5: error: assigning to 'v8::Primitive *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/iliakan/.node-gyp/4.1.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:414:12: note: in instantiation of function template specialization 'v8::Local<v8::Primitive>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../node-stringprep.cc:1:
In file included from ../node_modules/nan/nan.h:24:
In file included from /Users/iliakan/.node-gyp/4.1.0/include/node/node.h:42:
/Users/iliakan/.node-gyp/4.1.0/include/node/v8.h:221:5: error: assigning to 'v8::Boolean *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/iliakan/.node-gyp/4.1.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:424:12: note: in instantiation of function template specialization 'v8::Local<v8::Boolean>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../node-stringprep.cc:1:
In file included from ../node_modules/nan/nan.h:24:
In file included from /Users/iliakan/.node-gyp/4.1.0/include/node/node.h:42:
/Users/iliakan/.node-gyp/4.1.0/include/node/v8.h:221:5: error: assigning to 'v8::Function *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/iliakan/.node-gyp/4.1.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1514:12: note: in instantiation of function template specialization 'v8::Local<v8::Function>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(handle)->Get(kCallbackIndex)
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../node-stringprep.cc:1:
In file included from ../node_modules/nan/nan.h:24:
In file included from /Users/iliakan/.node-gyp/4.1.0/include/node/node.h:42:
/Users/iliakan/.node-gyp/4.1.0/include/node/v8.h:221:5: error: assigning to 'v8::Object *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/iliakan/.node-gyp/4.1.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1632:12: note: in instantiation of function template specialization 'v8::Local<v8::Object>::Local<v8::Value>' requested here
    return NanEscapeScope(handle->Get(NanNew(key)).As<v8::Object>());
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
3 warnings and 9 errors generated.
make: *** [Release/obj.target/node_stringprep/node-stringprep.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/iliakan/tmp/node_modules/node-xmpp-client/node_modules/node-xmpp-core/node_modules/node-stringprep
gyp ERR! node -v v4.1.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "node-xmpp-client"
npm ERR! node v4.1.0
npm ERR! npm  v2.14.3
npm ERR! code ELIFECYCLE

npm ERR! node-stringprep@0.7.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-stringprep@0.7.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-stringprep package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-stringprep
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/iliakan/tmp/npm-debug.log
```

**Comment by iliakan** [comment]
Could you please write back: is that a simple issue or won't be fixed soon?

I really need to know that to decide whether to rewrite a part of the project, or to keep waiting.

Thank you so so much!

**Comment by iliakan** [comment]
P.S. That was for Mac.

**Comment by sonnyp** [comment]
node-stringprep is not compatible with 4 yet indeed.
Not sure when I'll have time to look at it.

**Comment by iliakan** [comment]
Is it possible to disable stringprep?

**Comment by sonnyp** [comment]
@iliakan not easily but it is an easy to fix issue

**Comment by sonnyp** [comment]
Effort to make stringprep work with Node 4 is here https://github.com/node-xmpp/node-stringprep/pull/72

**Comment by sonnyp** [comment]
v2.0.0 is working with Node 4

**Comment by iliakan** [comment]
great! thanks!

**Comment by lloydwatkin** [comment]
:+1:
