### ISSUE TITLE
Integration test for server stopping during connection

### ISSUE THREAD

**Issue by lloydwatkin** [node-xmpp/node-xmpp-client#54]
```
    it('Errors when the server is stopped', function(done) {
        client = new Client({
            jid: jid,
            password: password,
            host: 'localhost'
        })
        client.on('end', function() {
            console.log(arguments)
            done()
        })
        helper.stopServer(function() {})
    })
```

1) Socket connections Errors when the server is stopped:
     Uncaught Error: XML parse error
      at Connection.error (/home/travis/build/node-xmpp/node-xmpp-client/node_modules/node-xmpp-core/lib/connection.js:389:24)
      at StreamParser.<anonymous> (/home/travis/build/node-xmpp/node-xmpp-client/node_modules/node-xmpp-core/lib/connection.js:214:14)
      at StreamParser.EventEmitter.emit (events.js:95:17)
      at StreamParser.error (/home/travis/build/node-xmpp/node-xmpp-client/node_modules/node-xmpp-core/lib/stream_parser.js:141:10)
      at SaxExpat.<anonymous> (/home/travis/build/node-xmpp/node-xmpp-client/node_modules/node-xmpp-core/lib/stream_parser.js:62:18)
      at SaxExpat.EventEmitter.emit (events.js:95:17)
      at null.<anonymous> (/home/travis/build/node-xmpp/node-xmpp-client/node_modules/node-xmpp-core/node_modules/ltx/lib/sax/sax_expat.js:16:14)
      at EventEmitter.emit (events.js:95:17)
      at Parser.parse (/home/travis/build/node-xmpp/node-xmpp-client/node_modules/node-xmpp-core/node_modules/ltx/node_modules/node-expat/lib/node-expat.js:18:22)
      at SaxExpat.write (/home/travis/build/node-xmpp/node-xmpp-client/node_modules/node-xmpp-core/node_modules/ltx/lib/sax/sax_expat.js:27:22)
      at StreamParser.write (/home/travis/build/node-xmpp/node-xmpp-client/node_modules/node-xmpp-core/lib/stream_parser.js:125:21)
      at Connection.onData (/home/travis/build/node-xmpp/node-xmpp-client/node_modules/node-xmpp-core/lib/connection.js:266:21)
      at Socket.EventEmitter.emit (events.js:117:20)
      at Socket.<anonymous> (_stream_readable.js:746:14)
      at Socket.EventEmitter.emit (events.js:92:17)
      at emitReadable_ (_stream_readable.js:408:10)
      at emitReadable (_stream_readable.js:404:5)
      at readableAddChunk (_stream_readable.js:165:9)
      at Socket.Readable.push (_stream_readable.js:127:10)
      at TCP.onread (net.js:528:21)

**Comment by lloydwatkin** [comment]
I think this is fixed by #140
