### ISSUE TITLE
BOSH client with authentication issues

### ISSUE THREAD

**Issue by 75lb** [node-xmpp/node-xmpp-client#83]
I am struggling to authenticate against an Openfire server.. to cut a long story short, after receiving the `success` stanza `Client.prototype._handleAuthState` emits an `auth` event but there are no listeners, so my script hangs - `online` is never emitted.. should i be listening on the `auth` event myself? 

my client
```js
var client = new Client({
	jid: "blah@blah",
	bosh: {
		url: "http://my.openfire.server.corp:7070/http-bind/"
	},
	password: 'whatever'
});
```
here is the output in `DEBUG=*` mode:
```
Cannot load StringPrep-0.5.4 bindings (using fallback). You may need to `npm install node-stringprep`
  node-stringprep Error: Symbol node_stringprep_module not found.
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (/Users/lloyd/Documents/channection/node_modules/node-xmpp-core/node_modules/node-stringprep/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/lloyd/Documents/channection/node_modules/node-xmpp-core/node_modules/node-stringprep/index.js:10:39)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12) +0ms
  node-stringprep Operation does not exist +191ms nodeprep [TypeError: Cannot read property 'StringPrep' of undefined]
  node-stringprep Operation does not exist +2ms resourceprep [TypeError: Cannot read property 'StringPrep' of undefined]
  node-stringprep Operation does not exist +1ms nameprep [TypeError: Cannot read property 'StringPrep' of undefined]
  xmpp:client:session start bosh connection +0ms
  xmpp:client:bosh process bosh server response <body xmlns="http://jabber.org/protocol/httpbind" xmlns:stream="http://etherx.jabber.org/streams" from="chat" authid="d611d327" sid="d611d327" secure="true" requests="2" inactivity="30" polling="5" wait="10" hold="1" ack="858084213" maxpause="300" ver="1.6"><stream:features><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>PLAIN</mechanism></mechanisms><compression xmlns="http://jabber.org/features/compress"><method>zlib</method></compression><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"/><session xmlns="urn:ietf:params:xml:ns:xmpp-session"/></stream:features></body> +29ms
  node-stringprep Operation does not exist +30ms nodeprep [TypeError: Cannot read property 'StringPrep' of undefined]
  node-stringprep Operation does not exist +0ms nameprep [TypeError: Cannot read property 'StringPrep' of undefined]
  xmpp:client:bosh process bosh server response <body xmlns="http://jabber.org/protocol/httpbind"><success xmlns="urn:ietf:params:xml:ns:xmpp-sasl"/></body> +55ms
ONNLINE
  xmpp:client:bosh process bosh server response <body xmlns="http://jabber.org/protocol/httpbind"/> +10s
  xmpp:client:bosh process bosh server response <body xmlns="http://jabber.org/protocol/httpbind"/> +10s
```
if i walk through the code, the `auth` event is fired in here
```js
Client.prototype._handleAuthState = function(stanza) {
    if (stanza.is('challenge', NS_XMPP_SASL)) {
       ...
    } else if (stanza.is('success', NS_XMPP_SASL)) {
        this.mech = null
        this.state = STATE_AUTHED
        this.emit('auth')
    } else {
        ...
    }
}
```
but there are no listeners, so the script completes with no further action.. the only listener on `auth` i could find in the library is here, but it is never fired:
```js
Session.prototype._addConnectionListeners = function (con) {
    ...
    if (con.startStream) {
        con.on('connect', function () {
            // Clients start <stream:stream>, servers reply
            con.startStream()
        })
        this.on('auth', function () {
            con.startStream()
        })
    }
}
```

**Comment by sonnyp** [comment]
@mweibel @75lb yes this is because we don't support stream restart. We're working on merging @mweibel work.
